name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "d0da87bb-adcf-40b0-a923-3fd2d1173ca4"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "6eb68a26d75d44ffae2d3c29d4979aa8"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
